const data = {
  products: [
    {
      name: "Dahi puri",
      slug: "Dahi-puri",
      category: "Veg",
      img: "/images/dahi-puri-chat.jpg",
      countInStock: 25,
      price: 9,
      brand: "Pani puri Wala",
      description: "testy snack with water",
    },
    {
      name: "Pasta",
      slug: "Pasta",
      category: "Veg",
      img: "/images/food_2.jpg",
      countInStock: 25,
      price: 8,
      brand: "Past Way",
      description: "Pasts with spice and test",
    },
    {
      name: "Chicken biryani",
      slug: "Chicken-biryani",
      category: "Non veg",
      img: "/images/food_1.jpg",
      countInStock: 0,
      price: 27,
      brand: "ABC Chicken",
      description: "Delhi best biryan",
    },
    {
      name: "Burger",
      slug: "chicken-burger",
      category: "Non veg",
      img: "/images/burger.jpg",
      countInStock: 10,
      price: 12,
      brand: "Burger Kong",
      description: "Burger you can trust on",
    },
    {
      name: "Pizza",
      slug: "Pizza",
      category: "Veg",
      img: "/images/pizza.jpg",
      countInStock: 25,
      price: 15,
      brand: "Pizza Hut",
      description: "Made with love and cheese",
    },
    {
      name: "Butter paneer",
      slug: "Butter-paneer",
      category: "Veg",
      img: "/images/paneer-butter.jpg",
      countInStock: 25,
      price: 18,
      brand: "Delhi Subway",
      description: "Butter n Butter only",
    },
    {
      name: "Fried Egg",
      slug: "Fried-Egg",
      category: "Non veg",
      img: "/images/fried-egg.jpg",
      countInStock: 25,
      price: 14,
      brand: "Eggo naz",
      description: "Made with love and cheese",
    },
  ],
};

export default data;
